### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by emresaracoglu** [mattermost/mattermost-webrtc#11]
Hi,

Removed in version 5.6. So do we have the chance to add this as an plugin?

**Comment by amyblais** [comment]
Hi @emresaracoglu,

Please see this Forum post on alternative options you can use for video calls: https://forum.mattermost.org/t/built-in-webrtc-video-and-audio-calls-removed-in-v5-6-in-favor-of-open-source-plugins/5998.

**Comment by cpanato** [comment]
closing this
