### ISSUE TITLE
SSL Certificates for dockerhost

### ISSUE THREAD

**Issue by kmsomashekar** [mattermost/mattermost-webrtc#7]
Hi,

I have running mattermost-webrtc as a docker on a host which has SSL certificate. However i when i try to initiate a call with mattermost, i am getting this error

2017/08/21 11:26:47 CEST] [EROR] /api/v4/webrtc/token:WebRTC.Token code=500 rid=ij11kpxhetbejru65oem6rwiur uid=um7x7zhsh7gxjbiqxxirujkw5o ip=105.18.0.116 We encountered an error while connecting to the server [details: Post https://mattermost.x.x:7089/admin: x509: certificate is valid for dockerhost, not mattermost.x.x]

I have a working certificate for my mattermost host. Please help me out.

Regards,
Krishna M S

**Comment by Aschen** [comment]
Hi,

Have you enable insecure connection in system console ?

In Mattermost System Console -> Security -> Connections:

    Enable Insecure Outgoing Connections: true

**Comment by stefanjauker** [comment]
how can i change the certificate

**Comment by cpanato** [comment]
closing this, this repo is not more maintained
